### PR TITLE
6 dict

### LINKED ISSUE #6: Create ivp_a1 dictionary using ivp_a1 Json schema in cognitionexplorer
The form exported from redcap only give you key of the choice to a multiple-choice question, not the value of the key. We need to figure out whether to add the value of the key to our json file and how to implement it.

### LINKED ISSUE #13: Create fvp_a1 json data file using all data in csv(raw) format in redcap
@mingjiecn will create fvp_a1 dictionary first in isssue #11

### PR DESCRIPTION
**Pull request by mingjiecn**
close #6

### CODE REVIEW

**Review by JasonFHough — CHANGES_REQUESTED** [review]
To be able to utilize this file within the Python package, the `ivp_a1.json` file needs to be referenced slightly differently when opening:

```
from pkg_resources import resource_filename

def ivp_a1():
    filepath = resource_filename(__name__, 'ivp_a1.json')
    with open(filepath) as f:
```

**Comment by mingjiecn** [comment]
> To be able to utilize this file within the Python package, the `ivp_a1.json` file needs to be referenced slightly differently when opening:
> 
> ```
> from pkg_resources import resource_filename
> 
> def ivp_a1():
>     filepath = resource_filename(__name__, 'ivp_a1.json')
>     with open(filepath) as f:
> ```

Fixed. Thank you!

**Review by JasonFHough — APPROVED** [review]

**Review by vsmalladi — CHANGES_REQUESTED** [review]
Can we add unit tests using https://docs.python.org/3/library/unittest.html?

We can add at least 1 example that works and one that doesn't  and check the json output.

**Comment by mingjiecn** [comment]
> Can we add unit tests using https://docs.python.org/3/library/unittest.html?
> 
> We can add at least 1 example that works and one that doesn't and check the json output.

unittest added

**Pull request merged**
