### PR TITLE
3/json-conversion

### LINKED ISSUE #3: implement conversion to JSON
Create a new python script: `redcap2json.py`

This script may utilize the core `nacc.uds3` module if needed.

Decide on usage of pandas or csv & json modules.

### LINKED ISSUE #9: Create ivp_a1 json data file using all data in csv(raw) format in redcap
after discussion with @JasonFHough  on 05/26/2020, we will use Pandas as the library to convert from scv to json: https://pandas.pydata.org/docs/index.html
We will use report contains all data in scv raw format as our source data.
@JasonFHough will try to create ivp_a1 json data file first with only keys.
After the dictionary is created then we can create ivp_a1 json data file with keys and values that can be used in cognitionexplorer.

### LINKED ISSUE #12: Create header dictionary using mixin Json schema in cognitionexplorer

### LINKED ISSUE #13: Create fvp_a1 json data file using all data in csv(raw) format in redcap
@mingjiecn will create fvp_a1 dictionary first in isssue #11

### PR DESCRIPTION
**Pull request by JasonFHough**
**What does this change do?** _Please be clear and concise._

Adds ability to convert a RedCap exported CSV file into the appropriate JSON format.

**Why was this change made?** _Including an issue number is sufficient. Otherwise, briefly explain the benefit of the change._

#13 , #9 
## Verification

_List the steps needed to make sure this thing works. Be precise._

1. Cd into the nacho folder
2. Run the following command (you may need to change the .csv file path): 
`clear && pip3 uninstall nacculator -y && pip3 install ../ && clear && python3 redcap2json.py --fileIn redcap-exported-file.csv`
3. The `.json` output file can be located in the same directory as `redcap2json.py`
- Verify the thing does this: ...
- Verify the thing does not do that: ...

## Affirmations

All of these should have a check by them. Any exception requires an explanation.

* [x] I matched the style of the existing code.
* [x] I added and updated any relevant documentation (inline, `README`, `CHANGELOG`, and such).
* [x] I used Python's type hinting.
* [x] I ran the automated tests and ensured they **ALL** passed.
* [x] I ran the linter and ensured my changes have not introduced **ANY** warnings or errors.
* [x] I have made an effort to minimize code changes and have not included any cruft (preference files, *.pyc files, old comments, print-debugging, unused variables).
* [x] I have made an effort maintain a clear commit history (haven't merged other branches or rebased improperly).
* [x] I have written the code myself or have given credit where credit is due.

### CODE REVIEW

**Comment by mingjiecn** [comment]
Can you also put a csv test file in the repo so we can use the same test file for testing purpose?

**Comment by JasonFHough** [comment]
> Can you also put a csv test file in the repo so we can use the same test file for testing purpose?

Sample CSV can be located in the tools folder. This file contains _all_ test data exported from redcap.

Note-- any CSV file that contains all the correct headers for the ivp_a1 form will work with the `redcap2json.py` script.

**Comment by mingjiecn** [comment]
image

Should you use "==" instead of  "is" here?

**Comment by JasonFHough** [comment]
Given that `dictionary.py` returns the correct list of headers from each form schema's `.json` file, `redcap2json.py` will parse each given form type at once.

Currently, the only form types accounted for are: ivp_a1, fvp_a1, master_id, and header.

**Comment by vsmalladi** [comment]
Closes #12

**Pull request merged**
